<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="PRG_TEST" Id="{2b0f2396-05a8-4641-ad59-d0377b4454be}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
    MovingAverage_Test : FB_MovingAverage_Test;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>